package com.example.myapplication.data

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import androidx.room.Transaction
import kotlinx.coroutines.flow.Flow

/**
 * Data Access Object for hike and route point persistence.
 *
 * Provides methods for inserting, querying, and transactionally
 * saving completed hikes along with their associated route points.
 */
@Dao
interface HikeDao {
    /**
     * Inserts a hike into the database.
     *
     * @param hike Hike entity to be inserted.
     * @return The autogenerated ID of the inserted hike.
     */
    @Insert
    suspend fun insertHike(hike: Hike): Long

    /**
     * Inserts multiple route points into the database.
     *
     * @param points List of route points associated with a hike.
     */
    @Insert
    suspend fun insertPoints(points: List<RoutePoint>)

    /**
     * Retrieves all hikes ordered by date, most recent first.
     *
     * Emits updates automatically when the underlying data changes.
     *
     * @return A [Flow] emitting the list of all recorded hikes.
     */
    @Query("SELECT * FROM hikes ORDER BY date DESC")
    fun getAllHikes(): Flow<List<Hike>>

    /**
     * Retrieves a single hike by its unique identifier.
     *
     * @param hikeId ID of the hike to retrieve.
     * @return The matching [Hike], or null if not found.
     */
    @Query("SELECT * FROM hikes WHERE id = :hikeId")
    suspend fun getHikeById(hikeId: Long): Hike?

    /**
     * Retrieves all route points associated with a specific hike.
     *
     * Route points are ordered chronologically by timestamp.
     *
     * @param hikeId ID of the hike whose route points should be returned.
     * @return List of route points for the given hike.
     */
    @Query("SELECT * FROM route_points WHERE hikeId = :hikeId ORDER BY timestamp ASC")
    suspend fun getPointsForHike(hikeId: Long): List<RoutePoint>

    /**
     * Saves a completed hike and its route points atomically.
     *
     * Inserts the hike, assigns its generated ID to each route point,
     * and then inserts all points in a single database transaction.
     *
     * @param hike Completed hike entity.
     * @param points Route points recorded during the hike.
     */
    @Transaction
    suspend fun saveCompletedHike(hike: Hike, points: List<RoutePoint>) {
        val hikeId = insertHike(hike)
        val pointsWithId = points.map { it.copy(hikeId = hikeId) }
        insertPoints(pointsWithId)
    }
}